### ISSUE TITLE
Add some hardware details to README

### ISSUE THREAD

**Issue by gwtaylor** [uoguelph-mlrg/PROTAX-GPU#19]
Some basic information of hardware requirements would be helpful to have in the README.

I think something along the lines of:

> To reproduce the BOLD dataset experiments, PROTAX-GPU requires a NVIDIA GPU with at least 16GB VRAM and CUDA compute capability 6.0 or later. This corresponds to GPUs in the NVIDIA Pascal, NVIDIA Volta™, NVIDIA Turing™, NVIDIA Ampere architecture, and NVIDIA Hopper™ architecture families.

**Comment by Cleanliness** [comment]
Added this paragraph to top of README
