### ISSUE TITLE
Jax error

### ISSUE THREAD

**Issue by hjarnek** [uoguelph-mlrg/PROTAX-GPU#30]
So, with PROTAX-CPU installed without any errors, I tried built-in model. I ran the command suggested in the readme file:

```
python scripts/process_seqs.py data/refs.aln models/params/model.npz models/ref_db/taxonomy37k.npz
```
with `refs.aln` from FinPROTAX in a new folder called `data`, as suggested. I got the following error:

<details>
<summary>Jax error</summary>

```bash
Traceback (most recent call last):
  File "/home/joel/.conda/envs/protax/lib/python3.12/site-packages/jax/_src/lax/lax.py", line 149, in broadcast_shapes
    return _broadcast_shapes_cached(*shapes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joel/.conda/envs/protax/lib/python3.12/site-packages/jax/_src/util.py", line 302, in wrapper
    return cached(config.trace_context() if trace_context_in_key else _ignore(),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joel/.conda/envs/protax/lib/python3.12/site-packages/jax/_src/util.py", line 296, in cached
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/joel/.conda/envs/protax/lib/python3.12/site-packages/jax/_src/lax/lax.py", line 155, in _broadcast_shapes_cached
    return _broadcast_shapes_uncached(*shapes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joel/.conda/envs/protax/lib/python3.12/site-packages/jax/_src/lax/lax.py", line 171, in _broadcast_shapes_uncached
    raise ValueError(f"Incompatible shapes for broadcasting: shapes={list(shapes)}")
ValueError: Incompatible shapes for broadcasting: shapes=[(40,), (37422, 83)]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/joel/PROTAX-GPU/scripts/process_seqs.py", line 12, in <module>
    classify_file(query_dir, model_dir, tax_dir)
  File "/home/joel/.conda/envs/protax/lib/python3.12/site-packages/protax/classify.py", line 71, in classify_file
    probs = get_probs(q, ok, tree, params, segnum, N).block_until_ready()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joel/.conda/envs/protax/lib/python3.12/site-packages/protax/model.py", line 130, in get_probs
    X = get_X(q, ok, tree, N, params.sc_mean, params.sc_var)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joel/.conda/envs/protax/lib/python3.12/site-packages/protax/model.py", line 32, in get_X
    dists = seq_dist(q, tree.refs, tree.ok_pos, ok_q)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joel/.conda/envs/protax/lib/python3.12/site-packages/protax/model.py", line 17, in seq_dist
    ok = jnp.bitwise_and(ok_query, ok)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joel/.conda/envs/protax/lib/python3.12/site-packages/jax/_src/numpy/ufunc_api.py", line 177, in __call__
    return call(*args)
           ^^^^^^^^^^^
  File "/home/joel/.conda/envs/protax/lib/python3.12/site-packages/jax/_src/numpy/ufuncs.py", line 1216, in _bitwise_and
    return lax.bitwise_and(*promote_args("bitwise_and", x, y))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joel/.conda/envs/protax/lib/python3.12/site-packages/jax/_src/numpy/util.py", line 362, in promote_args
    return promote_shapes(fun_name, *promote_dtypes(*args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joel/.conda/envs/protax/lib/python3.12/site-packages/jax/_src/numpy/util.py", line 227, in promote_shapes
    result_rank = len(lax.broadcast_shapes(*shapes))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Incompatible shapes for broadcasting: shapes=[(40,), (37422, 83)]
--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
```
</details>

**Comment by prajakta-1527** [comment]
Hi @hjarnek ,
I think the issue is with the length of query sequence and taxonomy database sequences(i.e `taxonomy37k.npz`). The sequence length in the file `FinPROTAX/modelCOIleray/refs.aln` is 157 while the sequence length in database is 329. So, I suggest you use `FinPROTAX/modelCOIfull/refs.aln` as the query file. It has the sequence length of 329 which matches to that of the database. 
Thanks for pointing this, I will add a validation check in the code so that the error is clear in such cases.

**Comment by hjarnek** [comment]
Hi, thanks for the tip Prajakta. Switching to `modelCOIfull` made it work (although I think the Leray fragment is actually 313 bp, while the full-length Folmer fragment is 658 bp).

This makes me wonder though, why the query sequences have to be the same length as the reference sequences? This is normally not the case when you assign taxonomy, but usually the query sequences can align locally to the references. As in the case of the 313 bp Leray fragment for instance, which can normally be queried directly against BOLD which consists mostly of 658 bp sequences. If query sequences and references need to be of the same length in PROTAX, what implications will that have for length variable markers like ribosomal rRNA markers?

I also wonder how to interpret the PROTAX output. The output I got from running this yielded a file called `pyprotax_results.csv` which looks like this:

  | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7
-- | -- | -- | -- | -- | -- | -- | -- | --
0 | 0 | 7 | 44 | 404 | 1647 | 4106 | 8689 | 21710
1 | 0 | 7 | 56 | 797 | 2853 | 6233 | 14870 | 47238
2 | 0 | 7 | 56 | 797 | 2853 | 6233 | 14870 | 47238
3 | 0 | 7 | 63 | 862 | 2986 | 6391 | 15221 | 48293
4 | 0 | 7 | 63 | 862 | 2986 | 6391 | 15221 | 48293
5 | 0 | 7 | 46 | 490 | 1936 | 4642 | 10194 | 28386

...etc downwards. Is this some sort of intermediate file? I was expecting a list of query sequence IDs with taxonomy assigned to them, and a probability value for each assigned taxonomic rank.

**Comment by prajakta-1527** [comment]
Hi @hjarnek, I think we can have a algorithm to allign query sequences logically to the database sequence. I am looking into it. Regarding your question about the output format, I will definately add a clear explanation to the output structure and will update the code to output the taxonomy assigned and corresponding probability for every query.

For now, this file shows the node numbers of the assigned taxonomy for the query. Here the 7 values corresponding to every row, denote the path from root to the classified taxonomy label. In the taxonomy tree, It starts from the `root[0]` , its children and so on till the classified node number.

 The `taxonomy.priors` file contains the mapping of node numbers to taxonomy labels. 
 For eg, query 1 is assigned to  `Insecta[7], Coleoptera[44], Ptiliidae[440], Acrotrichinae,[1647] Acrotrichini,[4106] Acrotrichis,[8689], Acrotrichis_rugulosa[21710]`

**Comment by gwtaylor** [comment]
Thanks @hjarnek for continuing to test this out and share feedback!

> This makes me wonder though, why the query sequences have to be the same length as the reference sequences? This is normally not the case when you assign taxonomy, but usually the query sequences can align locally to the references. As in the case of the 313 bp Leray fragment for instance, which can normally be queried directly against BOLD which consists mostly of 658 bp sequences.

I think this goes back to our discussion on alignment in #24. While what you suggest is perfectly reasonable, our code assumes that the sequences have been pre-aligned and formatted to be the same length. There is no alignment code in our codebase, though it would be nice to provide such functionality and I would welcome contributions that make this more useful outside of our COI focus!

> If query sequences and references need to be of the same length in PROTAX, what implications will that have for length variable markers like ribosomal rRNA markers?

At least for the present codebase, I think the implication would be that you would need to use your own alignment tool and pad the sequences so that they are the same length before using this code.

**Comment by hjarnek** [comment]
Thanks Graham & Prajakta for providing and maintaining this tool! I understand the argument about using pre-aligned sequences – fair enough. Let's continue the discussion elsewhere, as this is not a Jax error anymore.
