### ISSUE TITLE
Delineate hard requirements vs. recommended/tested versions of libraries

### ISSUE THREAD

**Issue by ieyriay** [uoguelph-mlrg/PROTAX-GPU#5]
Clearly delineate hard requirements vs. recommended/tested versions of libraries. Based on Slack discussion. For example, it was tested with CUDA Toolkit 12 and we recommend that but we know it will work with CUDA 11 (pending close of open issue #2).

**Comment by gwtaylor** [comment]
@Cleanliness and I had some Slack discussion about this. Need to bring that discussion into the README.

**Comment by Cleanliness** [comment]
Added as a note in installation instructions.
