### ISSUE TITLE
Implement CPU fallback

### ISSUE THREAD

**Issue by ieyriay** [uoguelph-mlrg/PROTAX-GPU#7]
Implement CPU fallback in case the user does not have access to GPU

**Comment by gwtaylor** [comment]
Priority is to get this on Linux and Mac, then Windows if possible.

**Comment by Cleanliness** [comment]
Simple CPU fallback added , see `knn_cpu.cpp`

**Comment by gwtaylor** [comment]
Thank you for adding this!

I was able to test on a Vector cpu node, and set up the environment from scratch. It pulled in the CPU version of JAX and I made it through wheel creation and installation of `protax`.

Unfortunately I am still hampered by #16 when I run `test_topk.py` so unable to verify completely that it works.
